### ISSUE TITLE
SQL Exception being thrown on program launch

### ISSUE THREAD

**Issue by tbertrand7** [tbertrand7/TTE_Solutions#11]
Stack trace below. Seems to be caused either by TrainController or in the DBInteraction.

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' ArrowDirection = '', NumPass = 0, temp = 0, status = '0', Occupied = '', TrainI' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:842)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:681)
	at trackModel.TrackDBInteraction.setSection(TrackDBInteraction.java:79)
	at trackModel.TrackModel.setBlock(TrackModel.java:79)
	at trainModel.TrainModel.run(TrainModel.java:251)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thatDaxton** [comment]
You need to pull a block before you update it, something is not following that practice.

**Comment by thatDaxton** [comment]
Gonna assume this is happening on TrainModel line 251

**Comment by mjt74** [comment]
Should be fixed. Sorry for the delay.
